In [1]:
import numpy as np

In [5]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [10]:
my_mat = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
my_mat 

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [12]:
arr_mat = np.array(my_mat)
arr_mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.zeros(((3,3,3)))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
np.eye(16)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [3]:
  np.random.rand(5)

array([0.46575643, 0.64553495, 0.72943315, 0.19509635, 0.08431001])

In [5]:
np.random.rand(5,5)

array([[0.4417306 , 0.12177234, 0.52832605, 0.36218901, 0.03731199],
       [0.4167731 , 0.59677645, 0.8781635 , 0.98634206, 0.94086441],
       [0.54054803, 0.56283546, 0.21691139, 0.24480747, 0.90138921],
       [0.77657054, 0.1318193 , 0.72464661, 0.72382207, 0.60202949],
       [0.89198589, 0.08770132, 0.42285984, 0.7421674 , 0.79467966]])

In [6]:
np.random.randint(1,100,5)

array([38,  2, 93, 62, 41])

In [10]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [11]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
arr.max()

24

In [13]:
arr.min()

0

In [14]:
arr.argmax()

24

In [15]:
arr.argmin()

0

In [3]:
array2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
array2d[0][1]

2

In [7]:
array2d[0,2]

3

In [8]:
array2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [9]:
array2d > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [10]:
arr_2d = np.arange(50).reshape(5,10)

In [11]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [13]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [3]:
abc= np.arange(50)

In [4]:
abc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])